name: quire_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.14.2
  introduction_screen: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  lint: ^1.6.0

flutter:
  uses-material-design: true
